### ISSUE TITLE
Weapons not working properly

### ISSUE THREAD

**Issue by mars22253** [daleao/modular-overhaul#100] opened 2023-11-09 14:31 UTC
Currently using the latest version of MARGO,
I currently have the weapons module off which is causing all club type weapons to not work properly (I have not checked them all but the ones I checked all had differing issues). Some of the issues are clubs being extremely fast, clubs being fast and only able to swing once and clubs being extremely slow. I'm not sure if any other weapons have been affected aside from clubs but swords seem to be okay. I switched on the weapons module to see if it would fix the issues, however when I swung my scythe nothing showed up but I heard the movement and the game froze and I could not move or open anything and had to manually shut my game, and when reopening the game I tested these issues and they still occurred.  There were no errors in my SMAPI log and no red lines.

**Comment by daleao** [comment] 2023-11-11 04:55
So your claim is that by not using this mod's weapon changes, your vanilla weapons are bugged?
Did you have the Combat module enabled at any point in the past?
Did you remove the mod altogether to make sure if it's even caused by this mod?
Also please include the log even if you don't see any errors.

**Comment by mars22253** [comment] 2023-11-11 13:44
In the current save file I had the combat module enabled from the start and only the weapons overhaul in combat off, and then when I started to get different weapons I realised there was a bug, which is when I tried enabling the weapons overhaul to see if the bug would be fixed. I've used MARGO in past save files, however not with 4.0 upwards and I never had these bugs.
I created a new save file with only MARGO and its dependencies, CJB item spawner and GMCM and spawned in weapons to test the issues with the weapons overhaul being off, which were the same as previous and I switched on the weapons overhaul after seeing the issues were the same and I used my scythe which froze my game and I had to manually end my game. In this save file when I switched on MARGO I think it may have just been the scythe that was bugged as I tested some other weapons before I tried the scythe, which was the only one that caused the issue of my game freezing. Here is the SMAPI log for the new save file, https://smapi.io/log/5aa6996b7d9f45ceaa5a656847d60ee8
I tried again with a new save file with the same mods as above and had the weapons module on from the start, which fixed the issue with the scythe freezing the game with the weapons overhaul on, here is the SMAPI log, https://smapi.io/log/2e3ff1ed5ce548b5bfc605e347813441
Here on this same save file I switched off the overhaul module causing all of the earlier bugs, and it also caused the scythe to freeze the game when the weapons overhaul was off rather then when the bug was caused when it was on earlier and here is the SMAPI log, https://smapi.io/log/0a3f81e178da40e5a312834470d4de01
I did not remove MARGO from my current save file I am playing on to avoid JSON shuffle, but I did as above to test the issues. Here is the SMAPI log of my current active save file that I am playing on with the latest MARGO version, https://smapi.io/log/65e8dfe4f1f149ed94736f00d79c6b1a

**Comment by daleao** [comment] 2023-11-11 20:31
There's some confusion between Combat **Module** and Weapon **Overhaul** feature, which is part of that module.
You mentioned several times a "Weapons Module", which was confusing.

So I tested Combat module enabled, without Weapon overhaul **off**, and indeed that causes an issue with the Scythe.
I will fix this in the next update.

But the scythe issue is unrelated to your club issue. If you still have issues with your clubs on a new save then let me know the steps to reproduce it.

**Comment by mars22253** [comment] 2023-11-12 00:32
Yes sorry about the confusion with combats module when writing, it was the weapons overhaul which I got mixed up with. To recreate the issues with the club, which the SMAPI log is above you just have to have the weapons overhaul off, which can be from the start or mid game, its just when the weapons overhaul is off and I spawned in some different clubs using the CJB item spawner. The most obvious ones are the lead rod and the kudgel as they were the first I saw, and you can just use the weapons as normal to see the issue. All of the clubs are not working properly, and you can spawn in any to see the different bugs which they all have.

**Comment by daleao** [comment] 2023-11-12 04:50
Ok I was able to reproduce. Issue will be resolved in next update.

**Closed by daleao** 2023-11-12 04:50 UTC
