### ISSUE TITLE
Level-Up Pop-Ups Double

### ISSUE THREAD

**Issue by wibbelkind** [daleao/modular-overhaul#138] opened 2023-12-19 18:18 UTC
So I've noticed as I was playing that whenever I was levelling up a skill, the pop-up during the night showed up twice. So it shows up, I close it, it pops up again.
I didn't think of this as an issue until I maxed my Mining skill for the second time and had to choose a profession - and then again. But since I'd already chosen Prospector, it only gave me the choice to choose Spelunker. I checked back in my profile after it saved - and I got assigned both professions!
I checked several times to make sure I didn't accidentally have MARGO installed twice - I don't. I don't know why it's running the professions pop-up twice.

I'll try and get a SMAPI of the next level-up if that helps.

**Comment by crowsWithHats** [comment] 2023-12-19 18:30
Can confirm that this is a problem, I was about to report this same issue.

**Comment by wibbelkind** [comment] 2023-12-19 18:47
Got a SMAPI, there seems to be an Entoarox Modding Utility error: [SMAPI log](https://smapi.io/log/38659de07a634a9dae0b982c5ad7eb32)

**Comment by Zelly9191** [comment] 2023-12-21 15:11
i'm having the same issue as well here is my log too.
[SMAPI-latest margo dupe level up bug.txt](https://github.com/daleao/modular-overhaul/files/13743295/SMAPI-latest.margo.dupe.level.up.bug.txt)

**Comment by LeaderOfTheCrazy** [comment] 2023-12-22 02:49
> Can confirm that this is a problem, I was about to report this same issue.
> 
> is there any way to like remove a profession for now? i wanna keep playing today but getting both professions feels cheap to say the least .w.
> 
> EDIT: i forgot mods can have specific commands and lo and behold, the professions commands allow for removing professions! love this mod 💜

How did you remove the professions? I've been using CJB Cheats to do it, but I can't do it with modded professions that were just integrated with the mod. I'm worried when I get to level 10, I'm going to end up getting both which is annoying but my biggest worry is when I get to the next prestige due to the graying out of the other profession (the one you picked the first time). I'm worried it's going to softlock me that day due to everything being grayed out and so I won't be able to click anything for the second pop up.

**Comment by daleao** [comment] 2023-12-22 15:33
I can't reproduce.
In both my debug modlist or curated modlist, on a new character, setting exp to level 10 on any skill and going to sleep I get prompted with each level up exactly one.

@wibbelkind You can't install a mod twice even if you wanted to. SMAPI will throw an error if you do that.

**Comment by VanguardTimaeus** [comment] 2023-12-22 15:40
For me, this issue only started occuring as after I did a prestige. It started happening with all skills after that, not just the one I reset.

**Comment by Zelly9191** [comment] 2023-12-22 16:50
i can confirm i have also done a prestige. https://smapi.io/log/3e4107f0999f4c5a8ee629d02298e87b

you can ignore the stuff regarding the luck skill that's just stuff fixing itself after other mod issues.

**Comment by BeldinBrightaxe** [comment] 2023-12-22 18:16
I am also having this issue. I just tried with a fresh SV install and only the following mods installed:
Console Commands
Error Handler
Modular Overhaul
Save Backup
SpaceCore

Also, this was on a different machine than my normal gaming computer.

**Comment by daleao** [comment] 2023-12-22 20:27
@BeldinBrightaxe can you please share the steps used to reproduce starting from new save?

**Comment by noracharles1934** [comment] 2023-12-22 21:08
I'm also having this issue -- I got the double pop-ups on every skill level-up, but it didn't seem to cause any problems until I got to Level 10 (for the first time on this save) and was required to choose 2 professions in order to advance to the next day, and then checked and realized I had been assigned both professions.

Then I tested with a brand new save using only this mod + Spacecore + CJB Item Spawner:
1. I copied my config file from my real save. I disabled all modules except Professions, but kept all Professions settings the same.
2. I started a new farm and woke up on Day 1, used CJB Item Spawner to get an iridium axe, chopped enough trees to get to Foraging Level 1, and went to bed.
3. Overnight, I got double pop-ups notifying me of the level-up.

I then repeated the same test using the Debug version of this mod, and got the double pop-ups again.

On both tests, I didn't get any error messages in the SMAPI window. Logs are here:
Regular: https://smapi.io/log/6758fddaf42e45f3902fd559f2457d1d
Debug: https://smapi.io/log/2c03a51aef194a519135652c4227eaff

(I also tried using CJB Cheats on Day 2 because I wanted to get up to Level 5 and actually choose a profession, but CJB Cheats required me to choose right then, rather than overnight. Only 1 pop-up that time!)

**Comment by BeldinBrightaxe** [comment] 2023-12-23 00:06
Here are my steps:

Fresh install of SV on my secondary computer.
Installed SMAPI
Installed MARGO
Started game and realized I forgot SpaceCore
Quit and installed SpaceCore.
Started a new game, standard farm.
One in game I jumped to the SMAPI console and typed: debug experience 0 15000
Back in game went to sleep.
Went through all 10 levels. Picked Harvester at level 5 and Agriculturist at level 10
Then it went through all the levels again. I was able to pick Harvester again at level 5, but couldn't pick Agriculturist at level 10 so had to pick Artisan.

**Comment by awkwardiiisms** [comment] 2023-12-23 02:19
Same problem here, only started occuring in the latest margo update, i haven't changed my mod folder or added/removed any other mods since updating, once i hit level 10 in another skill I'll get the smapi log

**Comment by daleao** [comment] 2023-12-23 05:57
Can everyone confirm if rolling back to the previous version resolves the issue?

**Comment by BeldinBrightaxe** [comment] 2023-12-23 06:44
Rolling back to 4.1.7 fixed it for my modded save.

**Comment by Jumping-notes** [comment] 2023-12-23 06:45
> Can everyone confirm if rolling back to the previous version resolves the issue?

I had the same problem with the previous version 4.1.7.
But the 4.1.7 problem is even more serious then, after my cooking skill have achieved 4 Level 10, cooking level will continue to cycle through levels 1-9.
When I updated to version 4.2, I didn't have the same problems as before, but as the title says, I got two prompts per level.
I'm focus on the content of each update, this problem probably appear in the added "agriculturist. Title. Prestiged. Male".
Of course, this is just my speculation, I hope it will be helpful to you.

**Comment by awkwardiiisms** [comment] 2023-12-23 08:28
> Can everyone confirm if rolling back to the previous version resolves the issue?

yes, using a previous version solves it

**Comment by daleao** [comment] 2023-12-23 18:52
Fixed in 4.2.1.

**Closed by daleao** 2023-12-23 18:52 UTC

**Comment by awkwardiiisms** [comment] 2023-12-23 21:22
> Fixed in 4.2.1.

thank you for your hard work!
