### ISSUE TITLE
about automate

### ISSUE THREAD

**Issue by 2970194508** [daleao/modular-overhaul#102] opened 2023-11-11 15:47 UTC
I manually added the machine name and found that they only work when I manually add items to the machine, and when I add items using automation, the Tinkerer skill does not take effect

**Comment by 2970194508** [comment] 2023-11-11 15:55
The same goes for some machines in PPJA, which only works when I manually add items to the machine, and the Artisan profession doesn't work when using automation

**Comment by daleao** [comment] 2023-11-11 18:13
I tested a Yogurt Jar and it works fine.
![image](https://github.com/daleao/modular-overhaul/assets/111105627/f6365893-0697-4aee-9928-56d7c9c59b65)
![image](https://github.com/daleao/modular-overhaul/assets/111105627/9932c4f2-ccaf-40b7-9b6c-2b045e2fe091)

**Comment by 2970194508** [comment] 2023-11-12 06:15
> 我测试了一个酸奶罐，它工作正常。 ![image](https://user-images.githubusercontent.com/111105627/282258936-f6365893-0697-4aee-9928-56d7c9c59b65.png) ![image](https://user-images.githubusercontent.com/111105627/282258940-9932c4f2-ccaf-40b7-9b6c-2b045e2fe091.png)

After I tested the yogurt can, the output quality is just as good as the input quality, but the time it takes for the machine to place the items manually will take less than the time for automation, and the filling machine some other machines only take effect when it is manual, even if I added them manually in the config file。

<img width="1280" alt="1699769676241" src="https://github.com/daleao/modular-overhaul/assets/150321134/47d8be01-3405-4cf3-bab0-ed981a50b44c">

**Comment by 2970194508** [comment] 2023-11-12 06:25
![Uploading 1699770264263.png…]()

**Comment by 2970194508** [comment] 2023-11-12 06:25
<img width="1280" alt="1699770264263" src="https://github.com/daleao/modular-overhaul/assets/150321134/3d71d3d1-e492-4355-b4c9-eb35ece4b505">

**Comment by daleao** [comment] 2023-11-12 17:18
Ok, thanks for the new details.
The shorter time when you use it manually is actually a bug. The automated time is correct. This bug will be fixed in the next update.
As for the issue with the Canned Meat, the problem is that Canned Meat is not marked as an Artisan Good. But this will also be fixed in the next update.

**Closed by daleao** 2023-11-12 17:18 UTC

**Comment by 2970194508** [comment] 2023-11-12 20:01
> 好的，感谢您提供新的细节。手动使用时时间较短实际上是一个错误。自动时间是正确的。此错误将在下一次更新中修复。至于肉罐头的问题，问题是肉罐头没有被标记为工匠商品。但这也将在下一次更新中修复。

PFM industrialized machines have the same problem when using automation (manually adding items will be affected by the craftsman's profession to reduce working hours, but automation will not), can you fix them as well
